;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		autopair-skip-close-maybe
		evil-change
		evil-force-normal-state
		evil-goto-mark-line
		evil-normal-state
		evil-previous-line
		evil-substitute
		))

(setq mc/cmds-to-run-once
      '(
		evil-mouse-drag-region
		evil-window-left
		))
